
services:
  postgres_strapi_blog:
    container_name: postgres_strapi_blog
    hostname: postgres_strapi_blog
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: blog-strapi-1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - C:/Documentos
    ports:
      - 5432:5432